---
name: commitlint
on:
  push:
    branches:
      - main

permissions:
  contents: read
  # Optional: allow read access to pull request.
  # Use with `only-new-issues` option.
  # pull-requests: read

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: ahmadnassri/action-commit-lint@v2
